Update fapi-oidc-conformance-test.yml

diff --git a/.github/workflows/fapi-oidc-conformance-test.yml b/.github/workflows/fapi-oidc-conformance-test.yml
--- a/.github/workflows/fapi-oidc-conformance-test.yml
+++ b/.github/workflows/fapi-oidc-conformance-test.yml
@@ -61,6 +61,10 @@ jobs:
       run: |
         INPUT_URL=${{github.event.inputs.download-url}}
         INPUT_TAG=${{github.event.inputs.tag}}
+        if [ -z "$INPUT_URL" ]; then
+          echo "Error: INPUT_URL is not provided or empty!"
+          exit 1
+        fi
         echo ">>> Downloading IS from provided URL..."
         echo ">>> Provide URL : ${INPUT_URL}"
         mkdir downloaded-product-is
